/**
 * Executive / Management Dashboard
 *
 * Cross-department KPI overview page for leadership roles.
 * Cardinal layout rule: data in center, Automa AI chat in right pane.
 *
 * RBAC: Visible to org_admin, executive, sales_manager, partner_admin, super_admin.
 * Access gating handled by canAccessSection() in users.ts via Sidebar navigation.
 *
 * Tabs:
 *   - Dashboard: Cross-department KPI metric tiles (total revenue, active accounts, team activity score, MRR, customer satisfaction, avg deal size)
 *   - Insights: Placeholder for Wave 2 cross-department analytics and trend analysis
 *   - Hunches: AI-generated business insights ranked by confidence and impact. Each hunch has a pattern + recommendation format.
 *   - Activities: Recent team/agent actions across all departments using staticActivityFeed from activity-utils.ts
 *   - ROI: Placeholder for Wave 3 ROI analysis (requires credit/metering system first)
 *
 * PRODUCTION NOTE: mockHunches will be generated by the backend AI analysis engine.
 * Management metrics will aggregate from all department data sources.
 */
import { useState, useMemo } from 'react';
import { LayoutDashboard, BarChart3, Lightbulb, Activity, DollarSign, TrendingUp, TrendingDown, Users, Target, Briefcase, ArrowUpRight, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Skeleton } from '@/components/ui/skeleton';
import { staticActivityFeed, getActivityColor } from '@/lib/activity-utils';
import { formatDistanceToNow } from 'date-fns';
import { useQuery } from '@tanstack/react-query';

/** Sub-navigation tabs for the management page — includes Hunches (AI insights) and ROI (Wave 3) */
const tabs = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { id: 'insights', label: 'Insights', icon: BarChart3 },
  { id: 'hunches', label: 'Hunches', icon: Lightbulb },
  { id: 'activities', label: 'Activities', icon: Activity },
  { id: 'roi', label: 'ROI', icon: DollarSign },
];

interface DashboardMetrics {
  conversationCounts: { total: number; open: number; closed: number; byChannel: Record<string, number> };
  messageCounts: { total: number; last30Days: number };
  campaignStats: { total: number; active: number; totalSent: number; totalReplied: number; replyRate: number; byDepartment: Record<string, { total: number; active: number; sent: number; replied: number; replyRate: number }> };
  agentCounts: { total: number; active: number; byDepartment: Record<string, number> };
  userCounts: { total: number; active: number };
}

/**
 * AI-generated business insights ("hunches") ranked by confidence percentage and impact level.
 * Each hunch contains:
 *   - pattern: The data trend the AI detected
 *   - recommendation: Actionable suggestion based on the pattern
 *   - confidence: 0-100 score indicating certainty of the pattern
 *   - impact: high/medium/low business impact assessment
 *
 * PRODUCTION NOTE: Will be generated by the backend AI analysis engine analyzing
 * CRM data, campaign results, and conversation patterns. Currently mock data.
 */
const mockHunches = [
  { id: 'h1', title: 'Lead Response Time Correlation', confidence: 92, impact: 'high', pattern: 'Leads contacted within 5 minutes have 3x higher conversion rate', recommendation: 'Prioritize sub-5-minute response times for all new leads' },
  { id: 'h2', title: 'Service-to-Sales Pipeline', confidence: 87, impact: 'high', pattern: 'Service customers who decline upsells are 40% more likely to buy a new vehicle within 6 months', recommendation: 'Create a follow-up campaign for declined service upsells' },
  { id: 'h3', title: 'Weekend Engagement Spike', confidence: 78, impact: 'medium', pattern: 'Widget interactions increase 65% on Saturday mornings', recommendation: 'Schedule high-impact campaigns for Saturday 9-11 AM' },
  { id: 'h4', title: 'Email vs SMS Response Rate', confidence: 85, impact: 'medium', pattern: 'SMS follow-ups get 4x the response rate vs email for leads under 30', recommendation: 'Default to SMS for younger demographics' },
  { id: 'h5', title: 'Inventory Price Sensitivity', confidence: 73, impact: 'medium', pattern: 'Vehicles priced 5-8% below market move 2x faster', recommendation: 'Review pricing strategy for slow-moving inventory' },
  { id: 'h6', title: 'Agent Handoff Quality', confidence: 68, impact: 'low', pattern: 'Conversations with 3+ agent handoffs have 50% lower satisfaction', recommendation: 'Limit handoffs to maximum 2 per conversation' },
];

export default function ManagementPage() {
  const [activeTab, setActiveTab] = useState('dashboard');

  const { data: metrics, isLoading: metricsLoading } = useQuery<DashboardMetrics>({
    queryKey: ['/api/metrics/dashboard'],
  });

  const managementMetrics = useMemo(() => {
    const stats = metrics?.campaignStats;
    const convCounts = metrics?.conversationCounts;
    const agentCounts = metrics?.agentCounts;
    const userCounts = metrics?.userCounts;
    return [
      { id: 'mgmt-1', label: 'Total Conversations', value: String(convCounts?.total ?? 0), trend: 'up' as const, icon: Briefcase },
      { id: 'mgmt-2', label: 'Active Users', value: String(userCounts?.active ?? 0), trend: 'up' as const, icon: Users },
      { id: 'mgmt-3', label: 'Active Agents', value: String(agentCounts?.active ?? 0), trend: 'up' as const, icon: Target },
      { id: 'mgmt-4', label: 'Active Campaigns', value: String(stats?.active ?? 0), trend: 'up' as const, icon: TrendingUp },
      { id: 'mgmt-5', label: 'Reply Rate', value: `${stats?.replyRate ?? 0}%`, trend: 'up' as const, icon: ArrowUpRight },
      { id: 'mgmt-6', label: 'Messages (30d)', value: String(metrics?.messageCounts?.last30Days ?? 0), trend: 'up' as const, icon: DollarSign },
    ];
  }, [metrics]);

  const renderDashboard = () => (
    <div className="p-6 space-y-6">
      <div>
        <h2 className="text-lg font-semibold mb-1">Management Dashboard</h2>
        <p className="text-sm text-muted-foreground">Cross-department KPIs and team performance</p>
      </div>
      {metricsLoading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {[...Array(6)].map((_, i) => (
            <Card key={i}>
              <CardContent className="p-4 space-y-2">
                <Skeleton className="h-3 w-24" />
                <Skeleton className="h-7 w-16" />
                <Skeleton className="h-3 w-20" />
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {managementMetrics.map(metric => (
          <Card key={metric.id} className="hover:shadow-md transition-shadow cursor-pointer" data-testid={`metric-tile-${metric.id}`}>
            <CardContent className="p-4">
              <div className="flex items-center justify-between mb-2">
                <p className="text-xs text-muted-foreground">{metric.label}</p>
                <metric.icon className="h-4 w-4 text-muted-foreground" />
              </div>
              <p className="text-2xl font-bold">{metric.value}</p>
            </CardContent>
          </Card>
        ))}
      </div>
      )}
    </div>
  );

  /** Insights tab — placeholder for Wave 2 cross-department analytics and performance benchmarking */
  const renderInsights = () => (
    <div className="p-6 flex items-center justify-center h-full">
      <div className="text-center space-y-3">
        <BarChart3 className="h-12 w-12 text-muted-foreground mx-auto" />
        <h3 className="text-lg font-medium">Management Insights</h3>
        <p className="text-sm text-muted-foreground max-w-sm">Cross-department analytics, trend analysis, and performance benchmarking.</p>
      </div>
    </div>
  );

  /** Hunches tab — AI-generated business insights with confidence bars and impact badges */
  const renderHunches = () => (
    <div className="p-6 space-y-4">
      <div>
        <h2 className="text-lg font-semibold mb-1">AI Hunches</h2>
        <p className="text-sm text-muted-foreground">Pattern-based insights ranked by confidence and impact</p>
      </div>
      <div className="space-y-3">
        {mockHunches.map(hunch => (
          <Card key={hunch.id} className="hover:shadow-md transition-shadow" data-testid={`hunch-card-${hunch.id}`}>
            <CardContent className="p-4">
              <div className="flex items-start justify-between gap-3 mb-2">
                <div className="flex items-center gap-2">
                  <Lightbulb className={cn('h-5 w-5 flex-shrink-0', hunch.confidence >= 85 ? 'text-amber-500' : hunch.confidence >= 70 ? 'text-amber-400' : 'text-amber-300')} />
                  <h3 className="text-sm font-semibold">{hunch.title}</h3>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  <Badge variant={hunch.impact === 'high' ? 'destructive' : 'secondary'} className="text-[10px]">{hunch.impact}</Badge>
                  <Badge variant="outline" className="text-[10px]">{hunch.confidence}%</Badge>
                </div>
              </div>
              <div className="space-y-2 ml-7">
                <div>
                  <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-medium">Pattern</p>
                  <p className="text-sm">{hunch.pattern}</p>
                </div>
                <div>
                  <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-medium">Recommendation</p>
                  <p className="text-sm text-primary/80">{hunch.recommendation}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );

  /** Activities tab — uses staticActivityFeed from activity-utils.ts to show recent team/agent actions across all departments */
  const renderActivities = () => (
    <div className="p-6 space-y-4">
      <h2 className="text-lg font-semibold">Recent Activities</h2>
      <div className="space-y-2">
        {staticActivityFeed.map(item => (
          <div key={item.id} className="flex items-start gap-3 p-3 border border-border rounded-lg" data-testid={`activity-item-${item.id}`}>
            <div className={cn('w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0', getActivityColor(item.type))}>
              <Activity className="h-4 w-4 text-white" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm">{item.description}</p>
              <p className="text-xs text-muted-foreground mt-1">
                {formatDistanceToNow(new Date(item.timestamp), { addSuffix: true })}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );

  /** ROI tab — placeholder for Wave 3 ROI analysis (requires credit/metering system to be built first) */
  const renderROI = () => (
    <div className="p-6 flex items-center justify-center h-full">
      <div className="text-center space-y-3">
        <DollarSign className="h-12 w-12 text-muted-foreground mx-auto" />
        <h3 className="text-lg font-medium">ROI Analysis</h3>
        <p className="text-sm text-muted-foreground max-w-sm">Return on investment tracking across all departments, campaigns, and AI initiatives.</p>
      </div>
    </div>
  );

  return (
    <div className="flex flex-col h-full" data-testid="management-page">
      <div className="border-b border-border px-6 pt-4">
        <h1 className="text-xl font-semibold mb-3">Management</h1>
        <div className="flex gap-1">
          {tabs.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={cn(
                'flex items-center gap-1.5 px-3 py-2 text-sm rounded-t-md transition-colors border-b-2',
                activeTab === tab.id
                  ? 'border-primary text-foreground font-medium'
                  : 'border-transparent text-muted-foreground hover:text-foreground'
              )}
              data-testid={`tab-mgmt-${tab.id}`}
            >
              <tab.icon className="h-4 w-4" />
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      <ScrollArea className="flex-1">
        {activeTab === 'dashboard' && renderDashboard()}
        {activeTab === 'insights' && renderInsights()}
        {activeTab === 'hunches' && renderHunches()}
        {activeTab === 'activities' && renderActivities()}
        {activeTab === 'roi' && renderROI()}
      </ScrollArea>
    </div>
  );
}
