// spec: specs/nexxus-full-coverage.md
// seed: tests/e2e/seed.spec.ts
// Generated by Playwright Test Generator with live-verified selectors

import { test, expect } from 'playwright/test';

const TEST_PASSWORD = "NexxusTest2026";

async function loginAs(page: import('playwright/test').Page, email: string) {
  const loginRes = await page.request.post('/api/auth/login', {
    data: { email, password: TEST_PASSWORD },
  });
  expect(loginRes.ok()).toBeTruthy();
  await page.addInitScript(() => {
    const prefix = 'nexxus_tour_dismissed_';
    const keys = ['main', 'teambox', 'my-work', 'sales', 'service', 'marketing',
      'management', 'agents', 'insights', 'settings', 'profile', 'usage'];
    for (const key of keys) localStorage.setItem(prefix + key, 'true');
  });
}

test.describe('Dashboard & Metrics', () => {
  test('Dashboard loads with metric tiles', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await expect(page.getByText('AI Key Metrics')).toBeVisible({ timeout: 10000 });
    await expect(page.getByText('Active Pipeline')).toBeVisible();
    await expect(page.getByText('Appointments Today')).toBeVisible();
    await expect(page.getByText('Open Escalations')).toBeVisible();
    await expect(page.getByText('Outbound Sent 24h')).toBeVisible();
    await expect(page.getByRole('textbox', { name: 'Ask me anything about your business' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Show KPIs for this month' })).toBeVisible();
  });

  test('Dashboard metrics are role-specific', async ({ page }) => {
    await loginAs(page, 'sales@serrahonda.com');
    await page.goto('/', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await expect(page.getByText('AI Key Metrics')).toBeVisible({ timeout: 10000 });
    const salesBody = await page.textContent('body') || '';
    expect(salesBody.length).toBeGreaterThan(100);
  });
});

test.describe('Settings Page', () => {
  test('Org Admin sees 6 settings tiles', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/settings', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.getByText('User Management').first().waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole('heading', { name: 'System Settings' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'User Management' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Organization' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Tools & Integrations' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Knowledge Base' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Notifications' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Appearance' })).toBeVisible();
  });

  test('Organization tile has CommGate toggle', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/settings', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.getByText('Organization').first().waitFor({ state: 'visible', timeout: 10000 });
    await page.locator('[data-testid="settings-tile-organization"]').click();
    await expect(page.locator('[data-testid="switch-communication-gate"]')).toBeVisible({ timeout: 5000 });
  });

  test('User Management shows user list', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/settings', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.getByText('User Management').first().waitFor({ state: 'visible', timeout: 10000 });
    await page.locator('[data-testid="settings-tile-users"]').click();
    await expect(page.locator('[data-testid="button-back-settings"]')).toBeVisible({ timeout: 5000 });
    const bodyText = await page.textContent('body') || '';
    expect(bodyText).toMatch(/@|Admin|Staff|Manager/);
  });

  test('Super Admin sees AI Configuration tile', async ({ page }) => {
    await loginAs(page, 'admin@nexxus.com');
    await page.goto('/settings', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.getByText('User Management').first().waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole('heading', { name: 'AI Configuration' })).toBeVisible();
  });
});

test.describe('TeamBox', () => {
  test('TeamBox shows conversations with filters', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/teambox', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.getByRole('button', { name: 'Conversations' }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole('button', { name: 'Conversations' })).toBeVisible();
    await expect(page.getByRole('button', { name: /Tasks/ })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Workflows' })).toBeVisible();
    await expect(page.getByRole('button', { name: /All \d+/ })).toBeVisible();
    await expect(page.getByRole('button', { name: /Open \d+/ })).toBeVisible();
    await expect(page.getByRole('button', { name: 'SMS' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Email' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Voice' })).toBeVisible();
    await expect(page.getByRole('textbox', { name: 'Search conversations...' })).toBeVisible();
  });

  test('Clicking conversation shows message thread', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/teambox', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.getByRole('button', { name: 'Conversations' }).waitFor({ state: 'visible', timeout: 10000 });
    const mcConv = page.getByRole('button', { name: /Michael Clark/ });
    if (await mcConv.count() > 0) {
      await mcConv.first().click();
      await expect(page.getByRole('textbox', { name: 'Write a reply...' })).toBeVisible({ timeout: 5000 });
    }
  });
});

test.describe('Department Pages', () => {
  test('Sales page loads', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/sales', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const bodyText = await page.textContent('body') || '';
    expect(bodyText.length).toBeGreaterThan(100);
  });

  test('Service page loads', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/service', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const bodyText = await page.textContent('body') || '';
    expect(bodyText.length).toBeGreaterThan(100);
  });

  test('Marketing page loads', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/marketing', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const bodyText = await page.textContent('body') || '';
    expect(bodyText.length).toBeGreaterThan(100);
  });

  test('Management page loads', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/management', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const bodyText = await page.textContent('body') || '';
    expect(bodyText.length).toBeGreaterThan(100);
  });
});

test.describe('Insights', () => {
  test('Insights page loads with metric content', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/insights', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const bodyText = await page.textContent('body') || '';
    expect(bodyText.length).toBeGreaterThan(100);
    const hasMetrics = /Lead|Pipeline|Conversion|Active|Total/i.test(bodyText);
    expect(hasMetrics).toBeTruthy();
  });
});

test.describe('Profile & Billing', () => {
  test('Profile page shows user info', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/profile', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const bodyText = await page.textContent('body') || '';
    expect(bodyText).toMatch(/Password|password|Profile/);
  });

  test('Billing page loads', async ({ page }) => {
    await loginAs(page, 'orgadmin@serrahonda.com');
    await page.goto('/billing', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const bodyText = await page.textContent('body') || '';
    expect(bodyText.length).toBeGreaterThan(50);
  });
});

test.describe('Widget & Landing', () => {
  test('Widget test page shows all dealer buttons', async ({ page }) => {
    await page.goto('/widget/test', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await expect(page.locator('[data-testid="btn-serra-honda"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="btn-serra-nissan"]')).toBeVisible();
    await expect(page.locator('[data-testid="btn-tony-serra-ford"]')).toBeVisible();
    await expect(page.locator('[data-testid="btn-hyundai-of-columbia"]')).toBeVisible();
    await expect(page.locator('[data-testid="btn-ford-of-columbia"]')).toBeVisible();
  });
});
